version: "3"
services:
  django:
    image: django:dev
    build:
      context: ./django_app
    ports:
      - '8081:8080'
    environment:
      - DEBUG=false
    volumes:
      - ./django_app:/opt/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      backend:
        aliases:
          - django
  django-worker:
    image: django:dev
    depends_on:
      - django
      - django-redis
    volumes:
      - ${TEST_PROJECT_PATH}/django_app:/opt/app
    command: celery -A django_app -b redis://redis:6379 worker -l info
    deploy:
      mode: replicated
      replicas: 3
    networks:
      backend:
        aliases:
          - django-worker
  portainer:
    image: portainer/portainer
    ports:
      - "9100:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        aliases:
          - portainer
  django-redis:
    image: redis:latest
    networks:
      backend:
        aliases:
          - redis
    ports:
      - "6380:6379"
  postgres:
    image: postgres:9.6
    volumes:
        - postgres-app-data:/var/lib/postgresql/data
    ports:
        - "5433:5432"
    networks:
      backend:
        aliases:
          - postgres
volumes:
  postgres-app-data:
networks:
  backend:
    driver: bridge